const carData = [
  {
    img: "images/id6.png",
    title: "VW ID.6 Crozz Pro",
    date: "2023",
    seats: "6",
    range: "565",
    design: "Electric",
    transmission: "Automatic",
    price: "8 million",
    vehicle: "volkswagen",
  },
  {
    img: "images/song_plus.png",
    title: "BYD Song Plus",
    date: "2025",
    seats: "5",
    range: "605",
    design: "Electric",
    transmission: "Automatic",
    price: "8.5 million",
    vehicle: "BYD",
  },
  {
    img: "images/seagull.png",
    title: "BYD Seagull",
    date: "2025",
    seats: "5",
    range: "405",
    design: "Electric",
    transmission: "Automatic",
    price: "3.6 million",
    vehicle: "BYD",
  },
  {
    img: "images/bz4x.png",
    title: "Toyota BZ4X",
    date: "2024",
    seats: "5",
    range: "550",
    design: "Electric",
    transmission: "Automatic",
    price: "6.8 million",
    vehicle: "toyota",
  },
  {
    img: "images/id4.png",
    title: "VW ID.4 Crozz Pro",
    date: "2023",
    seats: "5",
    range: "565",
    design: "Electric",
    transmission: "Automatic",
    price: "6.9 million",
    vehicle: "volkswagen",
  },
  {
    img: "images/leopard.png",
    title: "Leopard 03",
    date: "2025",
    seats: "5",
    range: "Long Range",
    design: "Hybrid",
    transmission: "Automatic",
    price: "8.9 million",
    vehicle: "BYD",
  },
];

export default carData;
