const carData = [
  {
    img: "images/id6-crozz.png",
    title: "VW ID.6 Crozz",
    date: "2023",
    seats: "6",
    range: "600",
    design: "Electric",
    transmission: "Automatic",
    price: "5.6 million",
    vehicle: "volkswagen",
  },
  {
    img: "images/eq.png",
    title: "Audi Q8 e-tron",
    date: "2023",
    seats: "5",
    range: "560",
    design: "Electric",
    transmission: "Automatic",
    price: "11 million",
    vehicle: "audi",
  },
  {
    img: "images/neta-u.png",
    title: "Neta V",
    date: "2023",
    seats: "5",
    range: "400",
    design: "Electric",
    transmission: "Automatic",
    price: "3 million",
    vehicle: "hozon",
  },
  {
    img: "images/toyota-bz4x_1.png",
    title: "Toyota BZ4X",
    date: "2023",
    seats: "5",
    range: "500",
    design: "Electric",
    transmission: "Automatic",
    price: "5–5.3 million",
    vehicle: "toyota",
  },
  {
    img: "images/id4.png",
    title: "VW ID.4",
    date: "2023",
    seats: "5",
    range: "550",
    design: "Electric",
    transmission: "Automatic",
    price: "5 million",
    vehicle: "volkswagen",
  },
  {
    img: "images/400.png",
    title: "Mercedes EQC 400",
    date: "2022",
    seats: "5",
    range: "370",
    design: "Electric",
    transmission: "Automatic",
    price: "11.9 million",
    vehicle: "mercedes",
  },
];

export default carData;
